version: '3.8'

services:
  db:
    image: postgres:13
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=blogdb
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app-network
  
  cerbos:
    image: ghcr.io/cerbos/cerbos:latest
    command: server --config=/app/config/config.yaml
    ports:
      - "3592:3592"
      - "3593:3593"
    volumes:
      - ./app/policies:/app/policies
      - ./app/config/config.yaml:/app/config/config.yaml
    networks:
      - app-network

  api:
    build: .
    ports:
      - "8000:8000"
    environment:
      - CERBOS_HOST=cerbos
      - DATABASE_URL=postgresql://postgres:password@db:5432/blogdb
    depends_on:
      db:
        condition: service_started
      cerbos:
        condition: service_started
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  postgres_data:
    driver: local
    driver_opts:
      type: none
      device: ${PWD}/data/postgres
      o: bind